---
title: "project"
author: "Jeff Lancaster, Tasheena Narraidoo, and Luke Haggerty"
date: "December 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(ggmap)
library(gridExtra)
library(viridis)
```

Group Evaluation Metrics:
  Background/Context
  Context in Slides
  Commentary on Exploratory Data Analysis: Visualization and Tables
  Explain Pitfalls and issues that we've run into
  Structure and Orgainzation of talk
  
  
#Exploratory Data Analysis

```{r}
test<-read_csv("./Data/test.csv")
train<-read_csv("./Data/train.csv")
colnames(test) #unique var is only ID
colnames(train) #unique vars are Category, Descript, Resolution

train <- train %>%
  mutate(Hour  = factor(hour(Dates), levels=0:23), Dates = as.POSIXct(round(Dates, units = "days")), 
         DayOfWeek = factor(DayOfWeek, levels=c("Monday","Tuesday","Wednesday","Thursday",
                                                "Friday","Saturday","Sunday")))

test <- test %>%
  mutate(Hour  = factor(hour(Dates), levels=0:23), Dates = as.POSIXct(round(Dates, units = "days")), 
         DayOfWeek = factor(DayOfWeek, levels=c("Monday","Tuesday","Wednesday","Thursday",
                                                "Friday","Saturday","Sunday")))

#Sorting into Crime Types
table(train$Category)

violent_crime <- c("ASSAULT","SEX OFFENSES FORCIBLE","ROBBERY")
property_crime<-c("BURGLARY","LARCENY/THEFT","VEHICLE THEFT","ARSON")


train$category_general <- ifelse(train$Category %in% violent_crime, "VIOLENT", ifelse(train$Category %in% property_crime, "PROPERTY", "OTHER"))
train$category_general<-as.factor(train$category_general)
```


```{r}
sfMap<-get_map(location="sanfrancisco", zoom= 12, source="google")
train2<-train[sample(nrow(train), 1000), ]

violent<-ggmap(sfMap, extent='device', legend="topleft") +
  stat_density_2d(data=filter(train2,category_general=="VIOLENT"),aes(x=X,y=Y,fill=..level..),size=.01,bins=16,geom="polygon",alpha=.2,show.legend = F) +
  scale_fill_continuous(low="black",high="red")+
  ggtitle('Violent Crime')

property<-ggmap(sfMap, extent='device', legend="topleft") +
  stat_density_2d(data=filter(train2,category_general=="PROPERTY"),aes(x=X,y=Y,fill=..level..),size=.01,bins=16,geom="polygon",alpha=.2,show.legend = F) +
  scale_fill_continuous(low="black",high="red")+
  ggtitle('Property Crime')

other<-ggmap(sfMap, extent='device', legend="topleft") +
  stat_density_2d(data=filter(train2,category_general=="OTHER"),aes(x=X,y=Y,fill=..level..),size=.01,bins=16,geom="polygon",alpha=.2,show.legend = F) +
  scale_fill_continuous(low="black",high="red")+
  ggtitle('Other Crime')

grid.arrange(violent,property,other,ncol=2) #basic 3 density maps
```

```{r}
weekend<-ggmap(sfMap, extent='device', legend="topleft") +
  stat_density_2d(data=filter(train2,DayOfWeek %in% c("Saturday","Sunday")),aes(x=X,y=Y,fill=..level..),size=.01,bins=16,geom="polygon",alpha=.2,show.legend = F) +
  scale_fill_continuous(low="black",high="red")+
  ggtitle('Weekend')

weekday<-ggmap(sfMap, extent='device', legend="topleft") +
  stat_density_2d(data=filter(train2,DayOfWeek%in%c("Monday","Tuesday","Wednesday","Thursday","Friday")), aes(x=X,y=Y,fill=..level..),size=.01,bins=16,geom="polygon",alpha=.2,show.legend = F) +
  scale_fill_continuous(low="black",high="red")+
  ggtitle('Weekday')

grid.arrange(weekend,weekday,ncol=2)
```
